---
title: "Ortolans and oilplants"
author: "Sirke"
date: "25 syyskuuta 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#tarvittavat paketit
paketit<-c("visreg","DHARMa","arm","performance","here","readr","tidyr","plyr","dplyr","vegan","ggplot2","lattice","psych","lme4","glmmTMB","MASS","MuMIn","mgcv","gamm4","glmmADMB")
lapply(paketit,library,character.only=T)

#aineisto
reg<-read.csv("ortolans.csv")
data<-read.csv("OrtolanBunting.csv")

#yhdistetään näistä region muuttuja mukaan aineistoon
data$region<-with(reg, region[match(data$id, id)])

names(data)
str(data)
summary(data)

#tarkasta kaikkien luokkien muoto
data$id<-as.factor(data$id)
#vuodelle oma faktori-muuttuja
data$fyear<-as.factor(data$year)

#valitaan aineisto vain vuodesta 2001 eteenpäin, NeoPrior-tietoa ei ole vuodelle 2000
data=subset(data,year!=2000)

#valitaan Pohjois-Karjala ja Keski-Suomi pois
data=subset(data,region!="PKA"&region!="KES")
data=droplevels(data)

#logaritmimuunnos pinta-alalle, luo uusi muuttuja
data$Larea=log(data$area)

#standardoi muuttujat uuteen data frameen niin edellisestä voi vielä tarkistaa
#mean on nolla ja sd on 0.5, Grueberin paperista otettu ohje
#area-muuttujaa eli pinta-alaa ei standardoida, niinkuin ei myöskään terri-muuttujaa 
#mä siis standardoin vuoden, toivottavasti se on ok?
dataS=data %>%mutate_at(c(2:3,5:7,9:21), funs(c(scale(.)*0.5))) #ei ehkä välttämätön tämä *0.5?

#tarkastan pari muuttujaa
mean(dataS$Ariver)
sd(dataS$Aroad)

mean(dataS$NeoPrior)
sd(dataS$NeoPrior)
#oikein menee
```



```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)

#tarkastellaan aineiston riippuvuussuhteita
pairs.panels(dataS[,c("terri","year","NeoPrior","agri5","shanG","open","region","prec","temp")],cex=4)
ggplot(dataS, aes(x=year,y=terri))+ geom_point() + geom_smooth()

#iso liuta erilaisia kuvaajia
xyplot(terri~year|id, data=dataS, type = c("p", "r"))
xyplot(terri~year, data=dataS, type = c("p", "r"))
xyplot(terri~neo, data=data, type = c("p", "r"))
xyplot(terri~neo|fyear, data=dataS, type = c("p", "r"))
xyplot(terri~neo|region, data=dataS, type = c("p", "r"))

xyplot(terri~X|Y, data=dataS, type = c("p", "r"))
xyplot(terri~prec|fyear, data=dataS, type = c("p", "r"))
xyplot(terri~NeoPrior|fyear, data=dataS, type = c("p", "r"))
xyplot(terri~shanG|fyear, data=dataS, type = c("p", "r"))
xyplot(terri~agri5|fyear, data=dataS, type = c("p", "r"))
xyplot(terri~temp|fyear, data=dataS, type = c("p", "r"))

#onko neo-kasvien määrissä muutoksia

p <- ggplot()
p <- p + geom_point(data = dataS, 
                    aes(y = terri, x = NeoPrior),
                    shape = 16, 
                    size = 2)
p <- p + xlab("NeoPrior") + ylab("Number of territories")
p <- p + theme(text = element_text(size=15)) 
p <- p + geom_smooth(data = dataS, 
                     aes(x = NeoPrior, 
                         y = terri))
p <- p + facet_grid(. ~ region, scales = "fixed")
p

###############################
gd <- dataS %>% 
  group_by(region, fyear) %>% 
  summarise(mter = mean(terri))
gd

ggplot(gd, aes(x = fyear, y = mter, group = region,color=region)) +
  geom_line() +
  geom_line(data = gd)


#kuinka paljon nollia?
sum(dataS$terri == 0) / nrow(dataS)
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
#mallit
N1=glmmTMB(terri ~ year
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N2=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE) 

N3=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year 
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N4=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region  + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N5=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG*year + open*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N6=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + shanG*year + open*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N7=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N8=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG*year + open*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N9=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + shanG*year + open*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

#Malli N9 on globaalimalli, joka sisältää kaiken.
#sen summarya tutkailemalla voi huomata jo nyt, jos malli olisi ihan päin honkia.
summary(N9)

#tarkistetaan ettei globaalimalli ole ylidispersoitunut
E2 <- resid(N9, type = "pearson")
N  <- nrow(dataS)
p  <- length(fixef(N9)$con) + 3  #2 sigmas and 1 size/k/theta NB parameter
sum(E2^2) / (N - p)
#globaalimalli on hieman alidispersoitunut, 0.74, onko tämä ongelma?

#How good is the model performing?
F9 <- fitted(N9)
par(mfrow = c(1,1), cex.lab = 1.5, mar = c(5,5,2,2))
plot(x = dataS$terri,
     y = F9,
     xlab = "Fitted values (with re)",
     ylab = "Number of territories",
     xlim = c(0,15),
     ylim = c(0,15))
abline(h = 0, lty = 2) 
cor(dataS$terri, F9)


#rankataan kaikki mallit niiden AICc arvoon perustuen. Mitä pienempi arvo sen parempi.
#AICc arvo arvioi mallien laadukkuutta suhteessa toisiinsa, se ei sinänsä kerro mitään siitä, onko yksikään malleista sopiva
#tutkijan on etukäteen pitänyt miettiä, että näissä malleissa on järkeä
output1<-model.sel(N1,N2,N3,N4,N5,N6,N7,N8,N9)
output1

#taulukkoa yritin tehdä..
knitr::kable(output1, digits = 2)

#paras malli on N7 mutta vain 0.23 AICc-yksikön päässä on toiseksi paras malli N4, joka olisi yksinkertaisempi ja melkein yhtä hyvä
#yksinkertaisuus on yleensä kaunista mutta silloin meidän mielenkiinnon kohteena oleva NeoPrior tippuisi pois tarkastelusta
#valitaan useampi paras malli ja haetaan niistä kompromissia

#tarkistan, onko tuloksissa eroa jos vertailisinkin AIC-arvoja. AICc arvo on korjattu huomioimaan pieni otoskoko. 
#Meillähän on aineistoa riittävästi, eli periaatteessa AICc arvon sijaan voisi käyttää AIC:täkin.
AIC(N1,N2,N3,N4,N5,N6,N7,N8,N9)
#ei eroa, samat kaksi mallia valikoituisivat jatkoon. Näillä mennään.

#valitaan jatkoon parhaimmat mallit, joilla alhaisimmat AICc-arvot, kriteerinä usein käytetty AICcdelta<4
#topmodels = get.models(output1,subset=delta<4)
#jatkoon valikoituu vain kaksi mallia

#tämä olisi vaihtoehtoinen kriteeri valita "parhaimmat" mallit, niiden "painoarvon" perusteella
topmodels = get.models(output1,cumsum(weight)<=0.95)
#tällä valinnalla mukaan tulisi kolme parasta mallia

#tehdään "parhaimmille" malleille model averaging eli käytetään useampaa (kahta) mallia muuttujien 
#estimaattien (vaikutuksen) arviointiin.
ave=model.avg(topmodels, revised.var = TRUE, fit=TRUE)
summary(ave)

#Tästä taulukosta katsotaan conditional average-arvoja (tällä menetelmällä muuttujan estimaatti arvioidaan vain 
#niistä malleista, joissa se esiintyy). Estimaatit NeoPrior-muuttujalle eroavat hieman averaging metodien välillä
#(full average metodissa muuttujan estimaatti arvioidaan kaikista malleista mutta niissä malleissa missä muuttujaa
#ei ole (eli N4) se saa arvon nolla).

#tässä siis eri muuttujille vielä kerran estimaatit (regressiokerroinko tämä on suomeksi?:)
coef(ave)
#ja niille luottamusvälit
confint(ave)
#jos luottamusvälien sisälle mahtuu nolla, ei muuttuja ole "merkitsevä", tai siis sen vaikutus on pieni eikä edes sen 
#merkkiä (negatiivinen vai positiivinen) pysty arvioimaan luotettavasti.
#year, Ariver, agri5, region, NeoPrior ja  temp selittävät osansa reviirien määrän vaihtelusta

#taulukkoa taas yritän tehdä..
ma_coefs <- coefTable(ave, full=F, adjust.se = TRUE)
coefnames <- row.names(ma_coefs)
ma_coefs <- as.data.frame(ma_coefs)
ma_coefs <- mutate(ma_coefs,
                   coefficient = coefnames,
                   t = Estimate / `Std. Error`,
                   p = pt(abs(t), df = 1397, lower.tail = FALSE), #en tiedä onko df oikein. Mutta sen muuttaminen ei muuta tuloksia?!
                   lower95 = Estimate - 1.96 * `Std. Error`,
                   upper95 = Estimate + 1.96 * `Std. Error`) %>% select(coefficient, Estimate, `Std. Error`, t, p, lower95, upper95)
knitr::kable(ma_coefs, digits = 2)

```


```{r}
#seuraavaksi ajattelin jatkaa paperin esimerkin mukaan ja käyttää model averaged mallia 
#piste-ennusteiden tekemiseen mutta mua häiritsee malliin päätyneet merkityksettömät interaktiot
#kokeilen myöhemmin tehdä samat mallit uudelleen ilman interaktioita

#Lasken kullekin alueelle ennustetut reviirimäärät kun NeoPrior-arvot ovat 0.1, 0.5 tai 0.9

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.1

TerriETHlow= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriETHlow
a=exp(TerriETHlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.1

TerriUUSlow= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriUUSlow
b=exp(TerriUUSlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.1

TerriPOHlow= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriPOHlow
c=exp(TerriPOHlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.1

TerriLOUlow= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriLOUlow
d=exp(TerriLOUlow)


NeoPrior0.1=cbind(a,b,c,d)
NeoPrior0.1

#########################

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.5

TerriETHmed= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriETHmed
a=exp(TerriETHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.5

TerriUUSmed= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriUUSmed
b=exp(TerriUUSmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.5

TerriPOHmed= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriPOHmed
c=exp(TerriPOHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.5

TerriLOUmed= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriLOUmed
d=exp(TerriLOUmed)


NeoPrior0.5=cbind(a,b,c,d)
NeoPrior0.5

#########################

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.9

TerriETHhigh= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriETHhigh
a=exp(TerriETHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.9

TerriUUShigh= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriUUShigh
b=exp(TerriUUShigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.9

TerriPOHhigh= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriPOHhigh
c=exp(TerriPOHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.9

TerriLOUhigh= -0.38 - 0.97*year - 0.16*Abuild + 0.24*Aroad + 0.07*Astream + 0.30*Ariver + 0.56*agri5 +1.48*LOU+
  1.99*POH + 1.47*UUS - 0.13*((NeoPrior-0.069)/(2*0.115447)) + 0.14*temp - 0.05*prec + 0.03*year*NeoPrior + 0.08*temp*year - 
  0.15*prec*year
TerriLOUhigh
d=exp(TerriLOUhigh)


NeoPrior0.9=cbind(a,b,c,d)
NeoPrior0.9

Neth=sum(dataS$region=="ETH")
Nlou=sum(dataS$region=="LOU")
Nuus=sum(dataS$region=="UUS")
Npoh=sum(dataS$region=="POH")
Ntot=Neth+Nlou+Nuus+Npoh

#Kaikkien alueiden yli laskettu ennustettu reviirimäärä kullekin neo-arvolle:

terri0.1=(TerriETHlow*Neth + TerriUUSlow*Nuus + TerriPOHlow*Npoh + TerriLOUlow*Nlou)/Ntot
exp(terri0.1)

terri0.5=(TerriETHmed*Neth + TerriUUSmed*Nuus + TerriPOHmed*Npoh + TerriLOUmed*Nlou)/Ntot
exp(terri0.5)

terri0.9=(TerriETHhigh*Neth + TerriUUShigh*Nuus + TerriPOHhigh*Npoh + TerriLOUhigh*Nlou)/Ntot
exp(terri0.9)

enn=c(exp(terri0.1),exp(terri0.5),exp(terri0.9))
enn
kasit=c("low","med","high")
ennusteet=data.frame(enn,kasit)
ennusteet  

preds=c(NeoPrior0.1,NeoPrior0.5,NeoPrior0.9)
preds
treat=rep(c("low","med","high"),each=4)
treat
region=rep(c("ETH","UUS","POH","LOU"),times=3)
region
predictions=data.frame(preds,treat,region)
predictions

#################################################
#luottamusvälien laskeminen

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.1

#luottamusvälin ala-arvo
confETHlow= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
confETHlow
a=exp(confETHlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.1

confUUSlow= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
confUUSlow
b=exp(confUUSlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.1

confPOHlow= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
confPOHlow
c=exp(confPOHlow)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.1

confLOUlow= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
confLOUlow
d=exp(confLOUlow)


conflower0.1=cbind(a,b,c,d)
conflower0.1

#########################
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.5

#luottamusvälin ala-arvo
confETHmed= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
a=exp(confETHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.5

confUUSmed= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
b=exp(confUUSmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.5

confPOHmed= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
c=exp(confPOHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.5

confLOUmed= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
d=exp(confLOUmed)


conflower0.5=cbind(a,b,c,d)
conflower0.5

#########################
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.9

#luottamusvälin ala-arvo
confETHhigh= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
a=exp(confETHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.9

confUUShigh= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
b=exp(confUUShigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.9

confPOHhigh= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
c=exp(confPOHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.9

confLOUhigh= -0.99 - 1.22*year - 0.48*Abuild - 0.07*Aroad - 0.19*Astream + 0.06*Ariver + 0.27*agri5 +0.79*LOU+
  1.22*POH + 0.80*UUS - 0.25*((NeoPrior-0.069)/(2*0.115447)) + 0.05*temp - 0.14*prec - 0.24*year*NeoPrior - 0.11*temp*year - 
  0.31*prec*year
d=exp(confLOUhigh)


conflower0.9=cbind(a,b,c,d)
conflower0.9

#luottamusvälit kaikkien alueiden yli

#alaraja
Neth=sum(dataS$region=="ETH")
Nlou=sum(dataS$region=="LOU")
Nuus=sum(dataS$region=="UUS")
Npoh=sum(dataS$region=="POH")
Ntot=Neth+Nlou+Nuus+Npoh

terri0.1=(confETHlow*Neth + confUUSlow*Nuus + confPOHlow*Npoh + confLOUlow*Nlou)/Ntot
exp(terri0.1)

terri0.5=(confETHmed*Neth + confUUSmed*Nuus + confPOHmed*Npoh + confLOUmed*Nlou)/Ntot
exp(terri0.5)

terri0.9=(confETHhigh*Neth + confUUShigh*Nuus + confPOHhigh*Npoh + confLOUhigh*Nlou)/Ntot
exp(terri0.9)

##########
#taulukoksi
lower95=c(conflower0.1,conflower0.5,conflower0.9)
lower95

##########
#taulukoksi 
ala95=c(exp(terri0.1),exp(terri0.5),exp(terri0.9))
ala95

#################################################
#luottamusvälien laskeminen
#luottamusvälin yläarvo

#eth
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.1

confETHlow= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
confETHlow
a=exp(confETHlow)
a
#uus
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.1

confUUSlow=  0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
confUUSlow
b=exp(confUUSlow)
b

#poh
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.1

confPOHlow=  0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
confPOHlow
c=exp(confPOHlow)

#lou
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.1

confLOUlow=  0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
confLOUlow
d=exp(confLOUlow)


confupper0.1=cbind(a,b,c,d)
confupper0.1

#########################
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.5

confETHmed= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
a=exp(confETHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.5

confUUSmed= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
b=exp(confUUSmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.5

confPOHmed= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
c=exp(confPOHmed)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.5

confLOUmed= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
d=exp(confLOUmed)


confupper0.5=cbind(a,b,c,d)
confupper0.5

#########################
year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=0;NeoPrior=0.9

confETHhigh= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
a=exp(confETHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=0;UUS=1;NeoPrior=0.9

confUUShigh= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
b=exp(confUUShigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=0;POH=1;UUS=0;NeoPrior=0.9

confPOHhigh= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
c=exp(confPOHhigh)

year=0;Abuild=0;Aroad=0;Astream=0;Ariver=0;agri5=0;temp=0;prec=0;LOU=1;POH=0;UUS=0;NeoPrior=0.9

confLOUhigh= 0.23 - 0.71*year +0.17*Abuild +0.55*Aroad +0.33*Astream + 0.54*Ariver + 0.84*agri5 +2.17*LOU+
  2.76*POH + 2.14*UUS - 0.01*((NeoPrior-0.069)/(2*0.115447)) + 0.23*temp +0.04*prec +0.29*year*NeoPrior +0.28*temp*year +0.01*prec*year
d=exp(confLOUhigh)

confupper0.9=cbind(a,b,c,d)
confupper0.9

##########
#taulukoksi
upper95=c(confupper0.1,confupper0.5,confupper0.9)
upper95


######################
#luottamusvälit kaikkien alueiden yli

Neth=sum(dataS$region=="ETH")
Nlou=sum(dataS$region=="LOU")
Nuus=sum(dataS$region=="UUS")
Npoh=sum(dataS$region=="POH")
Ntot=Neth+Nlou+Nuus+Npoh

terri0.1=(confETHlow*Neth + confUUSlow*Nuus + confPOHlow*Npoh + confLOUlow*Nlou)/Ntot
exp(terri0.1)

terri0.5=(confETHmed*Neth + confUUSmed*Nuus + confPOHmed*Npoh + confLOUmed*Nlou)/Ntot
exp(terri0.5)

terri0.9=(confETHhigh*Neth + confUUShigh*Nuus + confPOHhigh*Npoh + confLOUhigh*Nlou)/Ntot
exp(terri0.9)

#taulukoksi kaikki
predictions=cbind(predictions,lower95,upper95)
predictions

############
#taulukoksi
yla95=c(exp(terri0.1),exp(terri0.5),exp(terri0.9))
yla95

#taulukoksi kaikkien alueiden ylittävät ennusteet
ennus=cbind(ennusteet,ala95,yla95)
ennus

#kuvaajat
# Stacked barplot with multiple groups
ggplot(data=predictions, aes(x=treat, y=preds, fill=region)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(aes(ymin=lower95, ymax=upper95), width=.1,
                position=position_dodge(.9))


##kaikki alueet
ggplot(data=ennusteet, aes(x=kasit, y=enn)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(aes(ymin=ala95, ymax=yla95), width=.2,
                position=position_dodge(.9))
```


```{r}
##############################################################################
#yritän tehdä ennusteita model averaged mallilla

newdata <- expand.grid(NeoPrior= with(dataS, seq(min(NeoPrior), max(NeoPrior), length.out=3)),
                       year = mean(dataS$year),
                       Abuild = mean(dataS$Abuild),
                       Aroad = mean(dataS$Aroad),
                        Astream = mean(dataS$Astream),
                        Ariver = mean(dataS$Ariver),
                        agri5 = mean(dataS$agri5),
                        region = levels(dataS$region),
                        temp = mean(dataS$temp),
                        prec = mean(dataS$prec),
                        temp = mean(dataS$temp),
                       Larea=mean(dataS$Larea)) #tarviiko tämän?

pred.se <- predict(ave, type="link", re.form=NA,se.fit=TRUE, full=T, newdata) #ERROR: re.form not yet implemented
newdata$fit <- pred.se$fit
newdata$SE <- pred.se$se
newdata$upr=newdata$fit+1.96*newdata$SE
newdata$lwr=newdata$fit-1.96*newdata$SE

#pred.se <- predict(M.avg, type="response", se.fit=TRUE, re.form=NA, full=T, newdata)
#newdata$fit <- pred.se$fit
#newdata$SE <- pred.se$se
#newdata$upr=newdata$fit+1.96*newdata$SE
#newdata$lwr=newdata$fit-1.96*newdata$SE

#Note: when using glmmadmb(family="nbinom2") the use of type="response" is not possible, 
#but type="link" is. You could take the exp() of fit, SE, lwr, and upr, afterwards in 
#the newdata frame.

# full=T defines the use of  full model-averaged coefficients see [here][1] 
# (full=F would not work either, due to mixed models); type= "response" 
# calculates predictions on the response scale (i.e. uses the inverse link
# function, exp() in poisson); re.form = NA avoids the use of random factors
# (inclusion is not possible with se.fit=TRUE).
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
###########################################################################
#mallit glmmadmb-funktiolla
#mallit
N1=glmmadmb(terri ~ year
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N2=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS) 

N3=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N4=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region  + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N5=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG*year + open*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N6=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + shanG*year + open*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N7=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N8=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG*year + open*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

N9=glmmadmb(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + shanG*year + open*year + temp*year + prec*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2", 
           data=dataS)

#Malli N9 on globaalimalli, joka sisältää kaiken.
#sen summarya tutkailemalla voi huomata jo nyt, jos malli olisi ihan päin honkia.
summary(N9)

output1<-model.sel(N1,N2,N3,N4,N5,N6,N7,N8,N9)
output1

knitr::kable(output1, digits = 2)

AIC(N1,N2,N3,N4,N5,N6,N7,N8,N9)

topmodels = get.models(output1,cumsum(weight)<=0.95)

ave=model.avg(topmodels, revised.var = TRUE, fit=TRUE)
summary(ave)

coef(ave)
confint(ave)

#taulukkoa taas yritän tehdä..
ma_coefs <- coefTable(ave, full=T, adjust.se = TRUE)
coefnames <- row.names(ma_coefs)
ma_coefs <- as.data.frame(ma_coefs)
ma_coefs <- mutate(ma_coefs,
                   coefficient = coefnames,
                   t = Estimate / `Std. Error`,
                   p = pt(abs(t), df = 1397, lower.tail = FALSE), #en tiedä onko df oikein. Mutta sen muuttaminen ei muuta tuloksia?!
                   lower95 = Estimate - 1.96 * `Std. Error`,
                   upper95 = Estimate + 1.96 * `Std. Error`) %>% select(coefficient, Estimate, `Std. Error`, t, p, lower95, upper95)
knitr::kable(ma_coefs, digits = 2)

#predictions
newdata <- expand.grid(NeoPrior= with(dataS, seq(min(NeoPrior), max(NeoPrior), length.out=3)),
                       year = mean(dataS$year),
                       Abuild = mean(dataS$Abuild),
                       Aroad = mean(dataS$Aroad),
                       Astream = mean(dataS$Astream),
                       Ariver = mean(dataS$Ariver),
                       agri5 = mean(dataS$agri5),
                       region = levels(dataS$region),
                       temp = mean(dataS$temp),
                       prec = mean(dataS$prec),
                       Larea=mean(dataS$Larea)) #näissä ennusteissa on mukana pinta-ala offsetti, vrt. käsintehtyihin ennusteisiin

pred.se <- predict(ave, type="link", re.form=NA,se.fit=TRUE, full=T, newdata) 
#nämä ennusteet tehdään nyt full averaged eikä conditional arvoista.Varmaan sen takia hieman erilaiset?
newdata$fit <- pred.se$fit
newdata$SE <- pred.se$se
newdata$upr=newdata$fit+1.96*newdata$SE
newdata$lwr=newdata$fit-1.96*newdata$SE

newdata$fitX <-exp(newdata$fit)
newdata$SEX<-exp(newdata$SE)
newdata$uprX=exp(newdata$upr)
newdata$lwrX=  exp(newdata$lwr)
  

p1 <- ggplot(newdata, aes(x=NeoPrior, y=fitX, fill=region)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_errorbar(aes(ymin=lwrX, ymax=uprX), width=.1, position=position_dodge(2.0))
print(p1)

```


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
##############################################################################################################################
#mallit ilman interaktioita
N1=glmmTMB(terri ~ year
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N2=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE) 

N3=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior 
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N4=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region  + temp + prec
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N5=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG + open  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N6=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + shanG + open  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N7=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp + prec  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N8=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + shanG + open + temp + prec  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

N9=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + shanG + open + temp + prec  
           + offset(Larea) 
           + (1 + year| id), 
           family=nbinom2, 
           data=dataS, 
           REML=FALSE)

#globaalimalli
summary(N9)

#ranking
output1<-model.sel(N1,N2,N3,N4,N5,N6,N7,N8,N9)
output1

#topmodels, kokeilenkin 4 deltaAICc
topmodels = get.models(output1,subset=delta<4)

#model averaging
ave=model.avg(topmodels, revised.var = TRUE)
summary(ave)

#estimaatit ja luottamusvälit
coef(ave)
#ja niille luottamusvälit
confint(ave)

ma_coefs <- coefTable(ave, full=F, adjust.se = TRUE)
coefnames <- row.names(ma_coefs)
ma_coefs <- as.data.frame(ma_coefs)
ma_coefs <- mutate(ma_coefs,
                   coefficient = coefnames,
                   t = Estimate / `Std. Error`,
                   p = pt(abs(t), df = 1397, lower.tail = FALSE), #mikäs tää df olikaan? tulokset ei muutu vaikka olisi eri arvo
                   lower95 = Estimate - 1.96 * `Std. Error`,
                   upper95 = Estimate + 1.96 * `Std. Error`) %>% select(coefficient, Estimate, `Std. Error`, t, p, lower95, upper95)
knitr::kable(ma_coefs, digits = 2)

#nyt tulokset ovat hieman erilaisia
#Mutta edelleen year, river, agri5, region, NeoPrior ja temp ovat ainoita muuttujia, joilla luottamusvälin sisään 
#ei mahdu nollaa eli ovat vaikutukseltaan jonkun suuntaisia edes.

#mietin, pitäisikö mallia käyttää jonkin piste-estimaatin ennustamiseen? Kuten paperissa. Reviirien määrä isolle 
#ja pienelle NeoPrior-osuudelle?

summary(data$NeoPrior)
sd(data$NeoPrior)
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
#################################################################################################################

#Zuurin esimerkin mukaan analyysi menisi näin


#aloitetaan Poisson-mallilla
ZPois=glmer(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year + open*year + shanG*year  
           + offset(Larea) 
           + (1 + year| id), 
           family=poisson, glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
           data=dataS)

# Check for overdispersion
E2 <- resid(ZPois, type = "pearson")
N  <- nrow(dataS)
p  <- length(fixef(ZPois)) +2  #tuosta 2:sta en menisi takuuseen, että menikö oikein..
sum(E2^2) / (N - p)

#tai
check_overdispersion(ZPois)

#DHARMa-paketin kuvaajia mallin validointiin
simulateOutput=simulateResiduals(fittedModel = ZPois)
plot(simulateOutput)

testUniformity(simulationOutput = simulateOutput)
testDispersion(simulateOutput)
#en osaa näitä kuvaajia tulkita, näyttäisi siltä, että Poisson malli ei olisi ainakaan overdispersed. 
#Tarvitaanko siis neg.binomiaalijakauma?

# plot fitted values vs Pearson residuals
par(mfrow = c(1,1))
plot(x = fitted(ZPois),
     y = E2,
     xlab = "Fitted values",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Entäpä tämän tulkinta? Ymmärtääkseni näistä kuvista ei haeta residuaalien tasaista jakautumista 
#vaan mitä tahansa kuvioita. Onko tässä joku syy vaihtaa NB?

# plot Pearson residuals vs NeoPrior
par(mfrow = c(1,1))
plot(x = dataS$NeoPrior,
     y = E2,
     xlab = "Neoprior",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E2 ~ s(NeoPrior), data = dataS)
summary(T1)
plot(T1)

# plot Pearson residuals vs year
par(mfrow = c(1,1))
plot(x = dataS$year,
     y = E2,
     xlab = "year",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E2 ~ s(year), data = dataS)
summary(T1)
plot(T1)
#vuoden residuaaleissa taitaa olla kuvio?


#vaihdetaan NB
ZNeg=glmer(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year + open*year + shanG*year  
            + offset(Larea) 
            + (1 + year| id), 
            family=nbinom2(), glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=100000)),
            data=dataS)

#tai glmmTMB-funktiolla
ZNeg_TMB=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year + open*year + shanG*year  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)

# Check for overdispersion
E2 <- resid(ZNeg, type = "pearson")
N  <- nrow(dataS)
p  <- length(fixef(ZNeg)) + 2 + 1  #2 sigmas and 1 size/k/theta NB parameter (en taas olisi tästä niin varma)
sum(E2^2) / (N - p)
#Hmm.. underdispersion vain paheni?!

#nää ei toimi NB-malleille
#check_overdispersion(ZNeg)

#DHARMa-paketin kuvaajia mallin validointiin
#simulateOutput=simulateResiduals(fittedModel = ZNeg)
#plot(simulateOutput)

# Check for overdispersion
E2 <- resid(ZNeg_TMB, type = "pearson")
N  <- nrow(dataS)
p  <- length(fixef(ZNeg_TMB)$con) + 3  #2 sigmas and 1 size/k/theta NB parameter
sum(E2^2) / (N - p)
#hyvin erilainen dispersion statistic arvo glmmTMB-funktiolla, hmm?

summary(ZNeg)
summary(ZNeg_TMB)
#paljon varoituksia glmer-funktiosta vaikka malli konvergoituikin

# plot fitted values vs Pearson residuals
par(mfrow = c(1,1))
plot(x = fitted(ZNeg_TMB),
     y = E2,
     xlab = "Fitted values",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)

# plot Pearson residuals vs NeoPrior
par(mfrow = c(1,1))
plot(x = dataS$NeoPrior,
     y = E2,
     xlab = "Neoprior",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E2 ~ s(NeoPrior), data = dataS)
summary(T1)
plot(T1)

# plot Pearson residuals vs year
par(mfrow = c(1,1))
plot(x = dataS$year,
     y = E2,
     xlab = "year",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E2 ~ s(year), data = dataS)
summary(T1)
plot(T1)
#edelleen kuvio?

# plot Pearson residuals vs agri5
par(mfrow = c(1,1))
plot(x = dataS$agri5,
     y = E2,
     xlab = "agri5",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E2 ~ s(agri5), data = dataS)
summary(T1)
plot(T1)

AIC(ZPois,ZNeg_TMB)
#NB-malli näyttäisi olevan kuitenkin parempi, ainakin näin AIC arvoilla vertailtuna

# Is everything important?

Z1=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec*year+ open*year + shanG*year  
                 + offset(Larea) 
                 + (1 + year| id), 
                 family="nbinom2",
                 data=dataS)
Z2=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec + open*year + shanG*year 
                 + offset(Larea) 
                 + (1 + year| id), 
                 family="nbinom2",
                 data=dataS)
anova(Z1,Z2)

Z3=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec + open + shanG*year 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z2,Z3)

Z4=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior*year + temp*year + prec + open + shanG 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z3,Z4)

Z5=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp*year + prec + open + shanG 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z4,Z5)

Z6=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp + prec + open + shanG 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z5,Z6)

Z7=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp + prec + open 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z6,Z7)

Z8=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp + prec  
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z7,Z8)

Z9=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z8,Z9)

Z10=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region + NeoPrior 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z9,Z10)

Z11=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + region  + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z9,Z11)

Z12=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + agri5 + NeoPrior + temp 
            + offset(Larea) 
            + (1 + year| id), 
            family="nbinom2",
            data=dataS)
anova(Z9,Z12)

Z13=glmmTMB(terri ~ year + Abuild + Aroad + Astream + Ariver + region + NeoPrior + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z9,Z13)

Z14=glmmTMB(terri ~ year + Abuild + Aroad + Astream  + agri5 + region + NeoPrior + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z9,Z14)

Z15=glmmTMB(terri ~ year + Abuild + Aroad + Ariver + agri5 + region + NeoPrior + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z9,Z15)

Z16=glmmTMB(terri ~ year + Abuild  + Ariver + agri5 + region + NeoPrior + temp 
           + offset(Larea) 
           + (1 + year| id), 
           family="nbinom2",
           data=dataS)
anova(Z15,Z16)

Z17=glmmTMB(terri ~ year + Ariver + agri5 + region + NeoPrior + temp 
            + offset(Larea) 
            + (1 + year| id), 
            family="nbinom2",
            data=dataS)
anova(Z16,Z17)

Z18=glmmTMB(terri ~ Ariver + agri5 + region + NeoPrior + temp 
            + offset(Larea) 
            + (1 + year| id), 
            family="nbinom2",
            data=dataS)
anova(Z17,Z18)

ZF=glmmTMB(terri ~ year + Ariver + agri5 + region + NeoPrior + temp 
            + offset(Larea) 
            + (1 + year| id), 
            family="nbinom2",
            data=dataS)
summary(ZF)

# Model validation
E3 <- resid(ZF, type = "pearson")
N  <- nrow(dataS)
p  <- length(fixef(ZF)$con) + 3
sum(E3^2) / (N - p)


# Plot fitted values vs Pearson residuals
par(mfrow = c(1,1))
plot(x = fitted(ZF),
     y = E3,
     xlab = "Fitted values",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Hmmm.


# Plot fitted values vs observed data
par(mfrow = c(1,1))
plot(x = fitted(ZF),
     y = dataS$terri,
     xlab = "Fitted values",
     ylab = "Observed data",
     cex.lab = 1.5)
abline(h = 0, lty = 2)

# plot Pearson residuals vs NeoPrior
par(mfrow = c(1,1))
plot(x = dataS$NeoPrior,
     y = E3,
     xlab = "Neoprior",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E3 ~ s(NeoPrior), data = dataS)
summary(T1)
plot(T1)

# plot Pearson residuals vs year
par(mfrow = c(1,1))
plot(x = dataS$year,
     y = E3,
     xlab = "year",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E3 ~ s(year), data = dataS)
summary(T1)
plot(T1)
#edelleen kuvio?

# plot Pearson residuals vs agri5
par(mfrow = c(1,1))
plot(x = dataS$agri5,
     y = E3,
     xlab = "agri5",
     ylab = "Pearson residuals",
     cex.lab = 1.5)
abline(h = 0, lty = 2)
# Is there a pattern in here?
# Try fitting a smoother on the residuals
T1 <- gam(E3 ~ s(agri5), data = dataS)
summary(T1)
plot(T1)
```


```{r}
####################################################################
#PREDICTIONS

#Sketch fitted values
#A. Specify covariate values for predictions
#B. Create X matrix with expand.grid
#C. Calculate predicted values
#D. Calculate standard errors (SE) for predicted values
#E. Plot predicted values
#F. Plot predicted values +/- 2* SE 

#A: 
range(dataS$NeoPrior)

NeoPriorSeq <- seq(from = -0.3, to = 4.1, length = 3)
MyData <- expand.grid(NeoPrior  = NeoPriorSeq,
                      region      = levels(dataS$region),
                      year = 0, #tuleeko tähän nolla, tarkoittaen, että muut muuttujat ovat keskiarvoissaan
                      agri5 = 0, #ennusteet tehdään siis tavanomaiselle osapopulaatiolle?
                      temp= 0,
                      Ariver = 0)

#tai eri menetelmällä
MyData2 <- ddply(dataS, 
                .(year, region, agri5,Ariver,temp), summarize,
                NeoPrior = seq(min(NeoPrior), 
                                   max(NeoPrior),
                                   length = 3))
                     
#B. Create X matrix with expand.grid
X <- model.matrix(~  year + Ariver + agri5 + region + NeoPrior + temp, data = MyData)

#C. Calculate predicted values
MyData$eta  <- X %*% fixef(ZF)$con
MyData$ExpY <- exp( X %*% fixef(ZF)$con )

#D. Calculate standard errors (SE) for predicted values
#SE of fitted values are given by the square root of
#the diagonal elements of: X * cov(betas) * t(X)
MyData$SE <- sqrt(  diag(X %*%vcov(ZF)$con %*% t(X))  )

MyData$SeUp  <- exp(MyData$eta + 1.96 *MyData$SE) 
MyData$SeLo  <- exp(MyData$eta - 1.96 *MyData$SE) 

# And plot the whole thing
p <- ggplot()
p <- p + geom_point(data = dataS, 
                    aes(y = terri, x = NeoPrior),
                    shape = 1, 
                    size = 1)
p <- p + xlab("NeoPrior") + ylab("#terri")
p <- p + theme(text = element_text(size=15)) + theme_bw()
p <- p + geom_line(data = MyData, 
                   aes(x = NeoPrior, y = ExpY), 
                   colour = "black")

p <- p + geom_ribbon(data = MyData, 
                     aes(x = NeoPrior, 
                         ymax = SeUp, 
                         ymin = SeLo ),
                     alpha = 0.2)
p <- p + facet_grid(rows = vars(region) , scales = "fixed")
p


####################################################
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)
#####################################################
# Simulation

# This works:
simulate(ZF)  #It executes simulate.glmmTMB
#Random effects are also simulated from their estimated distribution

Nsim <- 1000
YNB <- simulate(ZF, nsim = Nsim, seed = 12345)
# Now we have 1000 simulated data sets from the model.
YNB[[1]]
YNB[[2]]

# What shall we do with these simulated data sets?
# We could calculate the number of zeros in each of the 1,000
# data sets.
zeros <- vector(length = Nsim)
for(i in 1:Nsim){
  zeros[i] <- sum(YNB[[i]] == 0)
}

table(zeros)
# From the 1,000 simulated data sets, in 1 simulated
# data sets we had 251 zeros. In 30-ish simulated data sets
# we had 300 zeros.

#Let's plot this as a table
plot(table(zeros), 
     xlab = "Number of zeros",
     ylab = "Frequency",
     xlim = c(350, 530))
points(x = sum(dataS$terri == 0), 
       y = 0, 
       pch = 16, 
       cex = 5, 
       col = 2)
# The red dot is the number of zeros in the original data set.

# Question: What does this tell you?

# Answer:   The data simulated from the NB model
#           does contain enough zeros.
# See you back on a ZIP course.

#Eli pitäisikö tässä tehdä zero inflated malli? tai toivottavasti gamm on hyvä ratkaisu? 
#Gamm-mallin validointiin jäin ennen tätä pähkäilyä
#Tuleeko Heikin graduun vain alun NB-mallit ja model averaging, kullekin muuttujalle confidence intervallit
#ja niistä tulkinta -> neonikotinoidien merkitys on pieni verrattuna muihin muuttujiin mutta selkeästi negatiivinen
```

